name: Check for updates and deploy to gh-pages
run-name: Trigger deploymeny by ${{ github.actor }}
on: 
  push:
    branches:
      - main
jobs:
  check-for-updates:
    runs-on: ubuntu-latest
    outputs:
      local_index_cksum: ${{ steps.fetch_local_cksum.outputs.local_index_cksum }}
      remote_index_cksum: ${{ steps.fetch_remote_cksum.outputs.remote_index_cksum }}
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Fetch cksum number for index.html on local branch
        id: fetch_local_cksum
        run: echo "local_index_cksum=$(cksum index.html | awk '{print $1}')" >> $GITHUB_OUTPUT
      - run: echo $local_index_cksum
      - name: Checkout to main and fetch cksum number for index.html on remote branch
        id: fetch_remote_cksum
        run: git checkout origin/main
      - run: echo "remote_index_cksum=$(cksum index.html | awk '{print $1}')" >> $GITHUB_OUTPUT
      - run: echo $remote_index_cksum
      - run: echo "🍏 This job's status is ${{ job.status }}."
  
  deploy:
    needs: [check-for-updates]
    if: ${{ needs.check-for-updates.outputs.local_index_cksum }}  != ${{ needs.check-for-updates.outputs.remote_index_cksum }}
    runs-on: ubuntu-latest
    steps:
      - name: Check out to branch that triggered the workflow
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
      - name: Push changes to gh-pages branch
        run: |
          git push origin HEAD:gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: echo "🍏 This job's status is ${{ job.status }}."
