name: Check for updates and deploy to gh-pages
run-name: Trigger deploymeny by ${{ github.actor }}
on: 
  push:
    branches:
      - main
jobs:
  check-for-updates:
    runs-on: ubuntu-latest
    outputs:
      local_index_cksum: ${{ steps.fetch_local_cksum.outputs.local_index_cksum }}
      previous_index_cksum: ${{ steps.fetch_previous_cksum.outputs.previous_index_cksum }}
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Fetch cksum number for index.html on local branch
        id: fetch_local_cksum
        run: echo "local_index_cksum=$(cksum index.html | awk '{print $1}')" >> $GITHUB_OUTPUT
      - name: Checkout to previous commit and fetch cksum number for index.html
        id: fetch_previous_cksum
        run: previous_commit=$(git log | grep commit | sed -n '3p' | awk '{print $2}')
      - run: echo $previous_commit
      - run: git checkout $previous_commit
      - run: echo "previous_index_cksum=$(cksum index.html | awk '{print $1}')" >> $GITHUB_OUTPUT
      - run: echo ${{ steps.fetch_local_cksum.outputs.local_index_cksum }}
      - run: echo ${{ steps.fetch_previous_cksum.outputs.previous_index_cksum }}
      - run: echo "🍏 This job's status is ${{ job.status }}."
  
  deploy:
    needs: [check-for-updates]
    if: ${{ needs.check-for-updates.outputs.local_index_cksum }} == ${{ needs.check-for-updates.outputs.previous_index_cksum }}
    runs-on: ubuntu-latest
    steps:
      - name: Check out to branch that triggered the workflow
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
      - name: Push changes to gh-pages branch
        run: |
          git push origin HEAD:gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: echo "🍏 This job's status is ${{ job.status }}."
