name: Deployment on merge with main
run-name: Trigger deploymeny by {{ github.actor }}
on: 
  push:
    branches:
      - main
jobs:
  Check for updates:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code and switch to main branch
        uses: actions/checkout@v4
      - run: |
          git fetch origin main
          git checkout main
      - run: echo "🚀 The ${{ github.repository }} repository has been checked out and the main branch has been switched to."
      - name: Fetch cksum for index.html in the main branch
        run: |
          cd ${{ github.workspace }}
          cksm=$(cksum index.html)
      - run: echo "🍏 This job's status is ${{ job.status }}."
